### ISSUE TITLE
Nested Wordpress user type

### ISSUE THREAD

**Issue by josephdburdick** [jferrettiboke/graphql-wordpress-api-example#1]
Thank you @jferrettiboke very much for putting this together 👍 .

Every `gql` example I come across is written one level deep. When I tried making a nested object for the Wordpress user's avatar I wasn't able to but worked around it by breaking it out into it's own type. Here's what that looks like:

```
  type WP_User {
    id: Int
    name: String
    url: String
    description: String
    link: String
    slug: String
    avatar_urls: WP_User__avatar
  }
  type WP_User__avatar {
    sm: String
    md: String
    lg: String
  }
```
Is there any other way to write that ^ ? It seems a little odd to me that I'm not allowed to nest inside of a type.

**Comment by jferrettiboke** [comment]
Don't do that. There is a better way to go.

Let to developers choose the size through the arguments. It's more elegant.

```graphql
{
  WP_users {
    id
    name
    
    # You can get a specific size, like so.
    avatar(size: SMALL)
    
    # If you don't specific any size, there is one by default: MEDIUM.
    # To see this working, just write the `avatar` field.
    
    # You could also want to fetch more than one avatar size at the same time.
    smallAvatar: avatar(size: SMALL)
    mediumAvatar: avatar(size: MEDIUM)
    largeAvatar: avatar(size: LARGE)
  }
}
```

The `size` argument is an enum definition which means we expect it to be exactly one of `SMALL`, `MEDIUM`or `LARGE`. By default, it will be `MEDIUM` (see the `avatar` field on `WP_User` type).

```graphql
type WP_User {
  id: Int!
  name: String
  avatar(size: WP_AvatarSize = MEDIUM): String
}
```

I just pushed a commit with this approach. So, check this [commit](https://github.com/jferrettiboke/graphql-wordpress-api-example/commit/92b401aff87c238cc0f5687fcc9cfbbf95951e4d) to see what is new and have a better understanding behind the scenes.

**Comment by josephdburdick** [comment]
Makes sense, thanks @jferrettiboke
