### ISSUE TITLE
Resolving Wordpress user

### ISSUE THREAD

**Issue by josephdburdick** [jferrettiboke/graphql-wordpress-api-example#2]
Hi @jferrettiboke, I'm wondering what is the most practical way of resolving a type (a Wordpress user) that will be present in many other places (pages, posts, comments, etc).
Below in bold is how I did it for WP_Page but it just seems _odd_ to me.
``` #connectors.js
import connectors from './connectors';
 
const resolvers = {
  Query: {
    WP_user(root, args) {
      return connectors.user(args)
        .then(user => user)
        .catch((err) => {
          throw new Error(err);
        });
    },
    WP_page(root, args) {
      return connectors.page(args)
        .then(page => page[0])
        .catch((err) => {
          throw new Error(err);
        });
    },
    WP_pages(root, args) {
      return connectors.pages(args)
        .then(pages => pages)
        .catch((err) => {
          throw new Error(err);
        });
    },
  },
  WP_User: {
    id(user) { return user.id; },
    name(user) { return user.name; },
    url(user) { return user.url; },
    slug(user) { return user.slug; },
    avatar_urls(user) {
      return {
        sm: user.avatar_urls['24'],
        md: user.avatar_urls['48'],
        lg: user.avatar_urls['96'],
      };
    },
  },
  WP_Page: {
    id(page) { return page.id; },
    slug(page) { return page.slug; },
    title(page) { return page.title.rendered; },
    content(page) { return page.content.rendered; },
    excerpt(page) { return page.excerpt.rendered; },
    type(page) { return page.type; },
    date(page) { return page.date; },
    date_gmt(page) { return page.date_gmt; },
    modified(page) { return page.modified; },
    modified_gmt(page) { return page.modified_gmt; },
    link(page) { return page.link; },
    **author(page) {
      return connectors.user({ id: page.author }).then(user => user);
    },**
    featured_media(page) { return page.featured_media; },
    parent(page) { return page.parent; },
    menu_order(page) { return page.menu_order; },
    comment_status(page) { return page.comment_status; },
    ping_status(page) { return page.ping_status; },
    template(page) { return page.template; },
  },
};

export default resolvers;

```
Is this done at the `gql` level as an input type definition or is it done inside resolvers.js by utilizing connectors.js like above? Thanks man. 🍰

**Comment by jferrettiboke** [comment]
You can resolve it where you want but in this case I suggest you resolving within the specific type definition (aka `WP_User`).

I just pushed a new [commit](https://github.com/jferrettiboke/graphql-wordpress-api-example/commit/868f9e0745778b7c467fa2671f78c8758e31b08a). Check it out.

> IMPORTANT NOTE!
>
> The changes that I made were without thinking in optimization. Of course, it could be done much better working with cached data using [DataLoader](https://github.com/facebook/dataloader). Read [this part](http://graphql.org/blog/rest-api-graphql-wrapper/#taming-pathological-queries) on [this blog post](http://graphql.org/blog/rest-api-graphql-wrapper) on the GraphQL official blog.
>
> Feel free to make a PR implementing `DataLoader` to this example.

**Comment by josephdburdick** [comment]
Thanks for clearing this up man, I'm closing this now.
